apiVersion: v1
kind: Namespace
metadata:
  name: sensors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensors-api
  namespace: sensors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensors-api
  template:
    metadata:
      labels:
        app: sensors-api
    spec:
      containers:
        - name: app
          image: 908518190934.dkr.ecr.eu-west-3.amazonaws.com/iot-playground-starter:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: sensors-api
  namespace: sensors
spec:
  type: LoadBalancer
  selector:
    app: sensors-api
  ports:
    - port: 80
      targetPort: 8080
