apiVersion: 1
datasources:
  - name: Prometheus
    uid: dew0ddwep0p34d
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "1s"
      minInterval: "1s"
