name: Destroy EKS Cluster

on:
  workflow_dispatch:
    inputs:
      region:
        description: "Région AWS"
        type: choice
        required: true
        default: eu-west-3
        options:
          - eu-west-3
      cluster_name:
        description: "Nom du cluster EKS"
        type: choice
        required: true
        default: iot-playground-starter-cluster
        options:
          - iot-playground-starter-cluster

permissions:
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      REGION: ${{ github.event.inputs.region }}
      CLUSTER: ${{ github.event.inputs.cluster_name }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Delete nodegroups (managed)
        shell: bash
        run: |
          set -euo pipefail
          NGS=$(aws eks list-nodegroups --cluster-name "$CLUSTER" --region "$REGION" --query 'nodegroups[]' --output text || true)
          if [ -n "${NGS}" ]; then
            for NG in ${NGS}; do
              echo "Deleting nodegroup: $NG"
              aws eks delete-nodegroup --cluster-name "$CLUSTER" --region "$REGION" --nodegroup-name "$NG"
              aws eks wait nodegroup-deleted --cluster-name "$CLUSTER" --region "$REGION" --nodegroup-name "$NG"
            done
          else
            echo "No managed nodegroups."
          fi

      - name: Delete Fargate profiles (if any)
        shell: bash
        run: |
          set -euo pipefail
          FPS=$(aws eks list-fargate-profiles --cluster-name "$CLUSTER" --region "$REGION" --query 'fargateProfileNames[]' --output text || true)
          if [ -n "${FPS}" ]; then
            for FP in ${FPS}; do
              echo "Deleting Fargate profile: $FP"
              aws eks delete-fargate-profile --cluster-name "$CLUSTER" --region "$REGION" --fargate-profile-name "$FP"
              aws eks wait fargate-profile-deleted --cluster-name "$CLUSTER" --region "$REGION" --fargate-profile-name "$FP"
            done
          else
            echo "No Fargate profiles."
          fi

      - name: Delete cluster
        shell: bash
        run: |
          set -euo pipefail
          echo "Deleting cluster: $CLUSTER"
          aws eks delete-cluster --name "$CLUSTER" --region "$REGION"
          aws eks wait cluster-deleted --name "$CLUSTER" --region "$REGION"
          echo "Cluster deleted."
